#!/bin/bash
set -eu

cd "${0%/*}"

export SSH_AUTH_SOCK=/run/user/$(id -u)/tkey-ssh-agent/sock

pubkey="$(ssh-add -L)"

git config --local commit.gpgsign true
git config --local tag.gpgsign true
git config --local gpg.format ssh
git config --local user.signingkey "$pubkey"
git config --local log.showSignature true
git config --local gpg.ssh.allowedSignersFile allowed_signers

email=$(git config user.email)
[[ -z "$email" ]] && exit 1

[[ ! -e allowed_signers ]] && touch allowed_signers
if ! grep -q "^$email" allowed_signers; then
  printf '%s namespaces="git" %s\n' "$email" "$pubkey" >>allowed_signers
fi
