#!/bin/bash
set -eu

# Get the agent installed and running:
#git clone https://github.com/tillitis/tkey-ssh-agent.git
#cd tkey-ssh-agent
#sudo make install
#sudo make reload-rules
#systemctl --user enable --now tkey-ssh-agent

# Now run this setup script in your repo
# Try showing the pubkey, you should get a pinentry for a USS when loading device app:
#SSH_AUTH_SOCK=/run/user/$(id -u)/tkey-ssh-agent/sock ssh-add -L
# Try committing
#SSH_AUTH_SOCK=/run/user/$(id -u)/tkey-ssh-agent/sock git commit -S -m msg
#git show

cd "${0%/*}"

pubkey=$HOME/tkey.pub

export SSH_AUTH_SOCK=/run/user/$(id -u)/tkey-ssh-agent/sock

if [[ ! -e "$pubkey" ]]; then
  ssh-add -L >"$pubkey"
fi

git config --local commit.gpgsign true
git config --local tag.gpgsign true
git config --local gpg.format ssh
git config --local user.signingkey "$pubkey"
git config --local log.showSignature true
git config --local gpg.ssh.allowedSignersFile allowed_signers

email=$(git config user.email)
[[ -n "$email" ]] || exit 1

[[ ! -e allowed_signers ]] && touch allowed_signers
if ! grep -q "^$email" allowed_signers; then
  printf '%s namespaces="git" %s\n' "$email" "$(cat "$pubkey")" >>allowed_signers
fi
